### ISSUE TITLE
Desktop icon missing on Flathub.org

### ISSUE THREAD

**Issue by AsciiWolf** [flathub/page.codeberg.Imaginer.Imaginer#2]
Imaginer desktop icon seems to be missing/set to default on the [Flathub page](https://flathub.org/apps/page.codeberg.Imaginer.Imaginer).

**Comment by 0xMRTT** [comment]
Pushed a new release which added an icon. Maybe it'll show soon

**Comment by AsciiWolf** [comment]
It looks like the issue got fixed. Thanks!
